services:
#    clanmanager.example:
#        class: ClanmanagerBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    security.access.account_voter:
        class:      ClanmanagerBundle\Security\Authorization\Voter\AccountVoter
        public:     false
        tags:
           - { name: security.voter }