#clanmanager:
#    resource: "@ClanmanagerBundle/Resources/config/routing.yml"
#    prefix:   /

clanmanager:
    resource: @ClanmanagerBundle/Controller/
    type:     annotation

#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation

logout:
    path:   /logout
