<?php

namespace ClanmanagerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ClanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClanRepository extends EntityRepository {

    public function findByPlayer($player) {
        return $this->createQueryBuilder('c')
                        ->select('c')
                        ->join('c.memberships', 'm')
                        ->where('m.player = :player')
                        ->andwhere('m.stop IS NULL')
                        ->setParameter('player', $player)
                        ->getQuery()
                        ->setMaxResults(1)
                        ->getOneOrNullResult();
    }

}
