<?php

namespace ClanmanagerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WarclanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WarclanRepository extends EntityRepository
{
}
