<?php

namespace ClanmanagerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WareventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WareventRepository extends EntityRepository {

    public function findByWarId($war_id) {
        return $this->createQueryBuilder('e')
                        ->select('e')
                        ->leftJoin('e.attacker', 'p')
                        ->leftJoin('p.warclan', 'c')
                        ->leftJoin('c.war', 'w')
                        ->where('w.id = :war_id')
                        ->addOrderBy('e.time','ASC')
                        ->addOrderBy('e.id','DESC')
                        ->setParameter('war_id', $war_id)
                        ->getQuery()
                        ->getResult();
    }

}
