<?php

namespace ClanmanagerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WareventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WareventRepository extends EntityRepository
{
}
